import crypto from 'node:crypto'
import compression from 'compression'
import cookieParser from 'cookie-parser'
import express, { type NextFunction, type Request, type Response } from 'express'
import helmet from 'helmet'
import { z } from 'zod'
import { config } from './config'
import { createRateLimiters } from './rateLimit'
import { createSupabaseAuthClient, getSupabaseAdmin, isSupabaseConfigured } from './supabase'
import type { Notification, Order, Product, User } from '../src/types'

export const isProd = config.isProduction
export const root = process.cwd()
export const app = express()
const limiters = await createRateLimiters()

type AppUser = User & { status:'active'|'suspended'|'deleted' }
type AuthedRequest = Request & { user?:AppUser;accessToken?:string }

app.disable('x-powered-by')
if(config.app.trustProxy)app.set('trust proxy',1)
app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false,frameguard:false}))
app.use(compression())
app.use(express.json({limit:'256kb'}))
app.use(cookieParser())
app.use('/api',limiters.api)

const cookieOptions={httpOnly:true,sameSite:config.auth.cookieSameSite,secure:config.auth.cookieSecure,path:'/'} as const
const setAuthCookies=(res:Response,session:{access_token:string;refresh_token:string;expires_in?:number},remember=true)=>{
  res.cookie(config.auth.sessionCookieName,session.access_token,{...cookieOptions,maxAge:(session.expires_in||3600)*1000})
  res.cookie(config.auth.refreshCookieName,session.refresh_token,{...cookieOptions,maxAge:remember?config.auth.rememberTtlMs:undefined})
}
const clearAuthCookies=(res:Response)=>{res.clearCookie(config.auth.sessionCookieName,{path:'/'});res.clearCookie(config.auth.refreshCookieName,{path:'/'})}
const supabaseUnavailable=(res:Response)=>res.status(503).json({message:'Supabase belum dikonfigurasi. Isi environment Supabase lalu jalankan migration server/schema.sql.'})
const requireSupabase=(_req:Request,res:Response,next:NextFunction)=>isSupabaseConfigured?next():supabaseUnavailable(res)
const parse=<T>(schema:z.ZodType<T>,body:unknown,res:Response):T|null=>{const result=schema.safeParse(body);if(!result.success){res.status(422).json({message:result.error.issues[0]?.message||'Data tidak valid.'});return null}return result.data}

const profileFromRelation=(value:unknown)=>Array.isArray(value)?value[0]||{}:(value||{}) as Record<string,unknown>
const loadAppUser=async(authUser:{id:string;email?:string|null}):Promise<AppUser>=>{
  const db=getSupabaseAdmin();const {data,error}=await db.from('users').select('id,username,email,role,status,balance,created_at,profiles(nickname,bio,avatar_url,banner_url,accent)').eq('id',authUser.id).single()
  if(error||!data)throw new Error('Profil pengguna tidak ditemukan. Jalankan trigger handle_new_user di Supabase.')
  const row=data as any;const profile=profileFromRelation(row.profiles) as any;const nickname=String(profile.nickname||row.username);const initials=nickname.split(/\s+/).map((part:string)=>part[0]).slice(0,2).join('').toUpperCase()
  return{id:String(row.id),username:String(row.username),email:String(row.email||authUser.email||''),nickname,role:row.role,balance:Number(row.balance),avatar:initials,bio:String(profile.bio||''),joinedAt:String(row.created_at),accent:String(profile.accent||'#8b5cf6'),avatarUrl:profile.avatar_url||undefined,bannerUrl:profile.banner_url||undefined,status:row.status}
}

app.use((req,res,next)=>{if(!req.cookies[config.csrf.cookieName])res.cookie(config.csrf.cookieName,crypto.randomBytes(24).toString('hex'),{httpOnly:false,sameSite:config.auth.cookieSameSite,secure:config.auth.cookieSecure,maxAge:config.csrf.ttlMs});next()})
app.use((req,res,next)=>{if(!['POST','PATCH','PUT','DELETE'].includes(req.method))return next();const origin=req.get('Origin');if(isProd&&origin&&!config.app.allowedOrigins.has(origin))return res.status(403).json({message:'Origin permintaan tidak diizinkan.'});const cookie=String(req.cookies[config.csrf.cookieName]||'');const header=String(req.get('X-CSRF-Token')||'');const a=Buffer.from(cookie);const b=Buffer.from(header);if(!cookie||!header||a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(403).json({message:'Sesi keamanan kedaluwarsa. Muat ulang halaman.'});next()})

app.use(async(req:AuthedRequest,res,next)=>{
  if(!isSupabaseConfigured)return next()
  let access=String(req.cookies[config.auth.sessionCookieName]||'');const refresh=String(req.cookies[config.auth.refreshCookieName]||'')
  if(!access&&!refresh)return next()
  try{
    const admin=getSupabaseAdmin();let authResult=access?await admin.auth.getUser(access):null
    if((!authResult||authResult.error)&&refresh){const auth=createSupabaseAuthClient();const refreshed=await auth.auth.refreshSession({refresh_token:refresh});if(refreshed.data.session){setAuthCookies(res,refreshed.data.session,true);access=refreshed.data.session.access_token;authResult=await admin.auth.getUser(access)}}
    const authUser=authResult?.data.user;if(authUser){req.accessToken=access;req.user=await loadAppUser(authUser)}
  }catch(error){console.error('[auth]',error instanceof Error?error.message:error);clearAuthCookies(res)}
  next()
})

const requireAuth=(req:AuthedRequest,res:Response,next:NextFunction)=>{if(!req.user)return res.status(401).json({message:'Silakan masuk untuk melanjutkan.'});if(req.user.status!=='active')return res.status(403).json({message:'Akun tidak aktif. Hubungi dukungan.'});next()}
const requireAdmin=(req:AuthedRequest,res:Response,next:NextFunction)=>{if(!req.user)return res.status(401).json({message:'Silakan masuk untuk melanjutkan.'});if(req.user.status!=='active'||req.user.role!=='admin')return res.status(403).json({message:'Akses admin diperlukan.'});next()}

const mapProduct=(row:any):Product=>({id:String(row.id),name:String(row.name),kind:'cookie',category:String(row.category),description:String(row.description),price:Number(row.price),stock:Number(row.stock),status:row.status,seller:{name:String(row.publisher_name),username:String(row.publisher_username),verified:Boolean(row.publisher_verified),rating:Number(row.rating)},rating:Number(row.rating),sold:Number(row.sold),createdAt:String(row.created_at),specs:Array.isArray(row.specs)?row.specs:[],icon:String(row.icon),accent:row.accent})
const productColumns='id,name,category,description,price,stock,status,specs,icon,accent,sold,rating,publisher_name,publisher_username,publisher_verified,created_at'
const relativeTime=(date:string)=>{const seconds=Math.max(1,Math.floor((Date.now()-new Date(date).getTime())/1000));if(seconds<60)return`${seconds} detik`;if(seconds<3600)return`${Math.floor(seconds/60)} menit`;if(seconds<86400)return`${Math.floor(seconds/3600)} jam`;return`${Math.floor(seconds/86400)} hari`}
const mapOrder=(row:any):Order=>{const snapshot=row.product_snapshot||{};return{id:String(row.display_id),productId:String(row.product_id),productName:String(snapshot.name||'Produk'),productIcon:String(snapshot.icon||'C'),date:new Date(row.created_at).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'}),createdAt:String(row.created_at),price:Number(row.total),status:row.status}}
const audit=async(req:AuthedRequest,action:string,targetType:string,targetId:string,before?:unknown,after?:unknown)=>{if(!req.user)return;const ipHash=crypto.createHmac('sha256',config.observability.auditIpHashSecret).update(req.ip||'unknown').digest('hex');await getSupabaseAdmin().from('admin_actions').insert({admin_id:req.user.id,action,target_type:targetType,target_id:targetId,before_state:before||null,after_state:after||null,ip_hash:ipHash})}

const loginSchema=z.object({identifier:z.string().min(3).max(120),password:z.string().min(8).max(128),remember:z.boolean().default(false)})
const registerSchema=z.object({username:z.string().regex(/^[a-z0-9_]{4,20}$/,'Username tidak valid.'),email:z.string().email('Email tidak valid.').max(120),password:z.string().min(8,'Password minimal 8 karakter.').max(128)})
const productInputSchema=z.object({name:z.string().min(4).max(80),category:z.string().min(2).max(40),description:z.string().min(20).max(400),price:z.number().int().min(1000).max(100000000),stock:z.number().int().min(0).max(999999),status:z.enum(['ready','limited','sold']),specs:z.array(z.string().min(2).max(80)).min(1).max(12),icon:z.string().min(1).max(2),accent:z.enum(['violet','pink','cyan','amber'])})
const userAdminUpdateSchema=z.object({role:z.enum(['user','moderator','admin']).optional(),status:z.enum(['active','suspended']).optional()}).refine(value=>Object.keys(value).length>0,'Tidak ada perubahan.')

app.get('/api/health',(_req,res)=>res.json({ok:true,time:new Date().toISOString(),environment:config.env,services:{supabase:isSupabaseConfigured?'configured':'not-configured',rateLimit:config.rateLimit.store}}))
app.get('/api/products',requireSupabase,async(_req,res)=>{const {data,error}=await getSupabaseAdmin().from('products').select(productColumns).order('created_at',{ascending:true});if(error)return res.status(500).json({message:'Katalog gagal dimuat.'});res.json({products:(data||[]).map(mapProduct)})})
app.get('/api/users/:username/public',requireSupabase,async(req,res)=>{const {data,error}=await getSupabaseAdmin().from('users').select('username,created_at,profiles(nickname,bio,avatar_url,banner_url,accent)').eq('username',String(req.params.username).toLowerCase()).eq('status','active').maybeSingle();if(error||!data)return res.status(404).json({message:'Profil tidak ditemukan.'});const profile=profileFromRelation((data as any).profiles) as any;res.json({profile:{username:data.username,nickname:profile.nickname||data.username,bio:profile.bio||'',avatarUrl:profile.avatar_url||null,bannerUrl:profile.banner_url||null,accent:profile.accent||null,joinedAt:data.created_at}})})

app.get('/api/auth/me',(req:AuthedRequest,res)=>res.json({user:req.user||null}))
app.post('/api/auth/login',requireSupabase,limiters.auth,async(req,res)=>{const body=parse(loginSchema,req.body,res);if(!body)return;const db=getSupabaseAdmin();let email=body.identifier;if(!email.includes('@')){const lookup=await db.from('users').select('email').eq('username',email.toLowerCase()).maybeSingle();if(lookup.error||!lookup.data)return res.status(401).json({message:'Email/username atau password tidak cocok.'});email=String(lookup.data.email)}const auth=createSupabaseAuthClient();const result=await auth.auth.signInWithPassword({email,password:body.password});if(result.error||!result.data.session||!result.data.user)return res.status(401).json({message:'Email/username atau password tidak cocok.'});const user=await loadAppUser(result.data.user);if(user.status!=='active')return res.status(403).json({message:'Akun tidak aktif. Hubungi dukungan.'});setAuthCookies(res,result.data.session,body.remember);res.json({user})})
app.post('/api/auth/register',requireSupabase,limiters.auth,async(req,res)=>{const body=parse(registerSchema,req.body,res);if(!body)return;const db=getSupabaseAdmin();const existing=await db.from('users').select('id').eq('username',body.username).maybeSingle();if(existing.data)return res.status(409).json({message:'Username sudah digunakan.'});const auth=createSupabaseAuthClient();const result=await auth.auth.signUp({email:body.email,password:body.password,options:{data:{username:body.username,nickname:body.username}}});if(result.error)return res.status(422).json({message:result.error.message});if(!result.data.user)return res.status(500).json({message:'Akun belum dapat dibuat.'});if(!result.data.session)return res.status(202).json({user:null,requiresEmailConfirmation:true});setAuthCookies(res,result.data.session,false);const user=await loadAppUser(result.data.user);res.status(201).json({user,requiresEmailConfirmation:false})})
app.post('/api/auth/logout',(_req,res)=>{clearAuthCookies(res);res.json({ok:true})})
app.post('/api/auth/forgot',requireSupabase,limiters.auth,async(req,res)=>{const body=parse(z.object({email:z.string().email()}),req.body,res);if(!body)return;const redirectTo=config.app.url?`${config.app.url}/reset-password`:undefined;await createSupabaseAuthClient().auth.resetPasswordForEmail(body.email,{redirectTo});res.json({ok:true,message:'Jika email terdaftar, instruksi akan dikirim.'})})
app.post('/api/auth/reset',requireSupabase,limiters.auth,async(req,res)=>{const body=parse(z.object({accessToken:z.string().min(20),password:z.string().min(8).max(128)}),req.body,res);if(!body)return;const db=getSupabaseAdmin();const authUser=await db.auth.getUser(body.accessToken);if(authUser.error||!authUser.data.user)return res.status(401).json({message:'Tautan pemulihan tidak valid atau sudah kedaluwarsa.'});const update=await db.auth.admin.updateUserById(authUser.data.user.id,{password:body.password});if(update.error)return res.status(422).json({message:update.error.message});res.json({ok:true})})

app.patch('/api/profile',requireSupabase,requireAuth,async(req:AuthedRequest,res)=>{const body=parse(z.object({nickname:z.string().min(2).max(32),username:z.string().regex(/^[a-z0-9_]{4,20}$/),bio:z.string().max(160),accent:z.enum(['#8b5cf6','#ec4899','#22d3ee','#f59e0b'])}),req.body,res);if(!body||!req.user)return;const db=getSupabaseAdmin();const userUpdate=await db.from('users').update({username:body.username}).eq('id',req.user.id);if(userUpdate.error)return res.status(userUpdate.error.code==='23505'?409:500).json({message:userUpdate.error.code==='23505'?'Username sudah digunakan.':'Profil belum disimpan.'});const profileUpdate=await db.from('profiles').update({nickname:body.nickname,bio:body.bio,accent:body.accent}).eq('user_id',req.user.id);if(profileUpdate.error)return res.status(500).json({message:'Profil belum disimpan.'});const authUser=(await db.auth.admin.getUserById(req.user.id)).data.user;res.json({user:authUser?await loadAppUser(authUser):null})})

const imageParser=express.raw({type:['image/jpeg','image/png','image/webp'],limit:config.uploads.profileMaxBytes})
function imageMeta(buffer:Buffer):{ext:string;width:number;height:number}|null{if(buffer.length>24&&buffer.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])))return{ext:'png',width:buffer.readUInt32BE(16),height:buffer.readUInt32BE(20)};if(buffer.length>30&&buffer[0]===0xff&&buffer[1]===0xd8){let offset=2;while(offset+9<buffer.length){if(buffer[offset]!==0xff){offset++;continue}const marker=buffer[offset+1];if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return{ext:'jpg',height:buffer.readUInt16BE(offset+5),width:buffer.readUInt16BE(offset+7)};const size=buffer.readUInt16BE(offset+2);if(size<2)break;offset+=2+size}}if(buffer.length>30&&buffer.toString('ascii',0,4)==='RIFF'&&buffer.toString('ascii',8,12)==='WEBP'){const kind=buffer.toString('ascii',12,16);if(kind==='VP8X')return{ext:'webp',width:1+buffer.readUIntLE(24,3),height:1+buffer.readUIntLE(27,3)}}return null}
app.post('/api/uploads/profile',requireSupabase,limiters.upload,requireAuth,imageParser,async(req:AuthedRequest,res)=>{const kind=req.query.kind==='banner'?'banner':'avatar';const buffer=req.body as Buffer;if(!req.user||!Buffer.isBuffer(buffer)||buffer.length<100)return res.status(422).json({message:'File gambar tidak valid.'});const meta=imageMeta(buffer);if(!meta)return res.status(422).json({message:'Format file tidak cocok dengan isi gambar.'});if(meta.width<config.uploads.imageMinDimension||meta.height<config.uploads.imageMinDimension)return res.status(422).json({message:`Resolusi minimal ${config.uploads.imageMinDimension} × ${config.uploads.imageMinDimension} piksel.`});if(meta.width>config.uploads.imageMaxDimension||meta.height>config.uploads.imageMaxDimension)return res.status(422).json({message:'Dimensi gambar terlalu besar.'});if(kind==='banner'&&meta.width/meta.height<config.uploads.bannerMinAspectRatio)return res.status(422).json({message:`Banner perlu rasio minimal ${config.uploads.bannerMinAspectRatio}:1.`});const db=getSupabaseAdmin();const objectPath=`profiles/${req.user.id}/${kind}-${crypto.randomUUID()}.${meta.ext}`;const upload=await db.storage.from(config.supabase.storageBucket).upload(objectPath,buffer,{contentType:req.get('Content-Type')||`image/${meta.ext}`,upsert:false});if(upload.error)return res.status(500).json({message:'Gambar gagal diunggah.'});const url=db.storage.from(config.supabase.storageBucket).getPublicUrl(objectPath).data.publicUrl;await db.from('profiles').update({[kind==='banner'?'banner_url':'avatar_url']:url}).eq('user_id',req.user.id);res.status(201).json({url,width:meta.width,height:meta.height})})

app.get('/api/orders',requireSupabase,requireAuth,async(req:AuthedRequest,res)=>{const {data,error}=await getSupabaseAdmin().from('orders').select('display_id,product_id,product_snapshot,total,status,created_at').eq('buyer_id',req.user!.id).order('created_at',{ascending:false});if(error)return res.status(500).json({message:'Riwayat pembelian gagal dimuat.'});res.json({orders:(data||[]).map(mapOrder)})})
app.post('/api/orders',requireSupabase,requireAuth,async(req:AuthedRequest,res)=>{const body=parse(z.object({productId:z.string().max(80),paymentMethod:z.enum(['balance','bank','ewallet'])}),req.body,res);if(!body||!req.user)return;const result=await getSupabaseAdmin().rpc('create_order_admin',{p_buyer_id:req.user.id,p_product_id:body.productId,p_payment_method:body.paymentMethod});if(result.error)return res.status(409).json({message:result.error.message});const order=Array.isArray(result.data)?result.data[0]:result.data;res.status(201).json({orderId:order.display_id,status:order.status,amount:Number(order.total)})})

app.get('/api/notifications',requireSupabase,requireAuth,async(req:AuthedRequest,res)=>{const {data,error}=await getSupabaseAdmin().from('notifications').select('id,type,title,body,read_at,created_at').eq('user_id',req.user!.id).order('created_at',{ascending:false}).limit(30);if(error)return res.status(500).json({message:'Notifikasi gagal dimuat.'});const notifications:Notification[]=(data||[]).map((row:any)=>({id:String(row.id),type:row.type,title:String(row.title),message:String(row.body),time:relativeTime(row.created_at),createdAt:String(row.created_at),read:Boolean(row.read_at)}));res.json({notifications})})
app.patch('/api/notifications/:id/read',requireSupabase,requireAuth,async(req:AuthedRequest,res)=>{await getSupabaseAdmin().from('notifications').update({read_at:new Date().toISOString()}).eq('id',String(req.params.id)).eq('user_id',req.user!.id);res.json({ok:true})})
app.post('/api/notifications/read-all',requireSupabase,requireAuth,async(req:AuthedRequest,res)=>{await getSupabaseAdmin().from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',req.user!.id).is('read_at',null);res.json({ok:true})})

app.get('/api/admin/users',requireSupabase,requireAdmin,async(_req,res)=>{const {data,error}=await getSupabaseAdmin().from('users').select('id,username,email,role,status,balance,created_at,profiles(nickname,avatar_url)').order('created_at',{ascending:false});if(error)return res.status(500).json({message:'Pengguna gagal dimuat.'});res.json({users:(data||[]).map((row:any)=>{const profile=profileFromRelation(row.profiles) as any;const nickname=String(profile.nickname||row.username);return{id:String(row.id),username:String(row.username),email:String(row.email),nickname,role:row.role,status:row.status,balance:Number(row.balance),joinedAt:String(row.created_at),avatar:nickname.slice(0,2).toUpperCase()}})})})
app.patch('/api/admin/users/:id',requireSupabase,requireAdmin,async(req:AuthedRequest,res)=>{const body=parse(userAdminUpdateSchema,req.body,res);if(!body||!req.user)return;const id=String(req.params.id);if(id===req.user.id&&(body.status==='suspended'||(body.role&&body.role!=='admin')))return res.status(422).json({message:'Admin tidak dapat menangguhkan atau menurunkan role akun sendiri.'});const db=getSupabaseAdmin();const before=await db.from('users').select('role,status').eq('id',id).maybeSingle();if(!before.data)return res.status(404).json({message:'Pengguna tidak ditemukan.'});const update=await db.from('users').update(body).eq('id',id).select('id,role,status').single();if(update.error)return res.status(500).json({message:'Pengguna belum diperbarui.'});await audit(req,'user.update','user',id,before.data,update.data);res.json({user:update.data})})

app.get('/api/admin/orders',requireSupabase,requireAdmin,async(_req,res)=>{const {data,error}=await getSupabaseAdmin().from('orders').select('display_id,product_id,product_snapshot,total,status,created_at').order('created_at',{ascending:false}).limit(100);if(error)return res.status(500).json({message:'Transaksi gagal dimuat.'});res.json({orders:(data||[]).map(mapOrder)})})
app.post('/api/admin/products',requireSupabase,requireAdmin,async(req:AuthedRequest,res)=>{const body=parse(productInputSchema,req.body,res);if(!body||!req.user)return;const base=body.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,52)||'cookie';const id=`${base}-${crypto.randomBytes(2).toString('hex')}`;const payload={id,...body,publisher_name:req.user.nickname,publisher_username:req.user.username,publisher_verified:req.user.role==='admin'};const result=await getSupabaseAdmin().from('products').insert(payload).select(productColumns).single();if(result.error)return res.status(422).json({message:result.error.message});await audit(req,'product.create','product',id,null,result.data);res.status(201).json({product:mapProduct(result.data)})})
app.patch('/api/admin/products/:id',requireSupabase,requireAdmin,async(req:AuthedRequest,res)=>{const body=parse(productInputSchema.partial().refine(value=>Object.keys(value).length>0,'Tidak ada perubahan.'),req.body,res);if(!body)return;const id=String(req.params.id);const db=getSupabaseAdmin();const before=await db.from('products').select(productColumns).eq('id',id).maybeSingle();if(!before.data)return res.status(404).json({message:'Produk tidak ditemukan.'});const result=await db.from('products').update(body).eq('id',id).select(productColumns).single();if(result.error)return res.status(422).json({message:result.error.message});await audit(req,'product.update','product',id,before.data,result.data);res.json({product:mapProduct(result.data)})})
app.delete('/api/admin/products/:id',requireSupabase,requireAdmin,async(req:AuthedRequest,res)=>{const id=String(req.params.id);const db=getSupabaseAdmin();const before=await db.from('products').select(productColumns).eq('id',id).maybeSingle();if(!before.data)return res.status(404).json({message:'Produk tidak ditemukan.'});const result=await db.from('products').delete().eq('id',id);if(result.error)return res.status(409).json({message:'Produk masih digunakan transaksi dan tidak dapat dihapus.'});await audit(req,'product.delete','product',id,before.data,null);res.json({ok:true})})

app.use('/api',(_req,res)=>res.status(404).json({message:'Endpoint tidak ditemukan.'}))
app.use((error:unknown,_req:Request,res:Response,_next:NextFunction)=>{console.error(error);res.status(500).json({message:'Server sedang bermasalah. Coba beberapa saat lagi.'})})
