import { Activity, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, BadgeCheck, Check, CircleDollarSign, Clock3, Eye, FileWarning, MoreHorizontal, Package, Search, ShieldAlert, ShieldCheck, ShoppingBag, UserCheck, UserRound, Users, X } from 'lucide-react'
import { useState } from 'react'
import { Badge, Button, Input, Modal } from '../components/UI'
import { StatusBadge } from '../components/StatusBadge'
import { useToast } from '../context/ToastContext'
import { products, recentOrders, rupiah } from '../data'
import { api } from '../lib/api'

const adminUsers = [
  { id:'u1', name:'Raka Aditya', username:'raka_sore', email:'raka@langgor.store', role:'Player', status:'active', joined:'Mei 2025', orders:12 },
  { id:'u2', name:'Pandu Pratama', username:'panduplays', email:'pandu@example.com', role:'Player', status:'active', joined:'Jan 2026', orders:28 },
  { id:'u3', name:'Alya Rani', username:'alyarn', email:'alya@example.com', role:'User', status:'review', joined:'Agu 2026', orders:2 },
  { id:'u4', name:'Bimo Arga', username:'bimoarga', email:'bimo@example.com', role:'User', status:'suspended', joined:'Jul 2026', orders:0 },
]

type Tab = 'overview'|'users'|'listings'|'transactions'

export function AdminPage() {
  const [tab,setTab]=useState<Tab>('overview')
  const [query,setQuery]=useState('')
  const [action,setAction]=useState<{type:'suspend'|'restore'|'approve'|'reject';id:string;label:string}|null>(null)
  const [loading,setLoading]=useState(false)
  const {showToast}=useToast()
  const execute=async()=>{if(!action)return;setLoading(true);try{await api('/admin/action',{method:'POST',body:JSON.stringify(action)});showToast({tone:'success',title:'Aksi admin tercatat',message:`${action.label} berhasil diperbarui.`});setAction(null)}catch(error){showToast({tone:'error',title:'Aksi ditolak',message:error instanceof Error?error.message:'Coba lagi.'})}finally{setLoading(false)}}
  const users=adminUsers.filter(u=>(u.name+u.email+u.username).toLowerCase().includes(query.toLowerCase()))
  return <div className="content-page admin-page page-enter">
    <div className="admin-banner"><div><span className="eyebrow"><i/> ADMIN CONTROL / LIVE</span><h1>Monitor, periksa, putuskan.</h1><p>Aksi sensitif diverifikasi role di server dan disimpan ke audit log.</p></div><div className="admin-identity"><ShieldCheck/><span><small>ACTIVE ROLE</small><strong>Super Admin</strong></span></div></div>
    <nav className="admin-tabs" aria-label="Menu admin">{([['overview','Ringkasan',Activity],['users','Pengguna',Users],['listings','Cookie',Package],['transactions','Transaksi',ShoppingBag]] as const).map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon/>{label}{id==='listings'&&<span>8</span>}</button>)}</nav>

    {tab==='overview'&&<>
      <section className="admin-metrics"><article><span className="admin-metric__icon violet"><Users/></span><span><small>TOTAL USERS</small><strong>12,482</strong><em className="up"><ArrowUpRight/> 8.2%</em></span></article><article><span className="admin-metric__icon cyan"><UserCheck/></span><span><small>ACTIVE USERS</small><strong>8,291</strong><em className="up"><ArrowUpRight/> 4.6%</em></span></article><article><span className="admin-metric__icon pink"><ShoppingBag/></span><span><small>TOTAL ORDER</small><strong>32,918</strong><em className="up"><ArrowUpRight/> 12.1%</em></span></article><article><span className="admin-metric__icon amber"><CircleDollarSign/></span><span><small>REVENUE / BULAN</small><strong>Rp284Jt</strong><em className="down"><ArrowDownRight/> 1.4%</em></span></article></section>
      <section className="admin-overview-grid"><article className="admin-chart"><div className="card-heading"><div><span className="eyebrow">ORDER VOLUME / 7 HARI</span><h2>Transaksi tetap stabil.</h2></div><select><option>7 hari</option><option>30 hari</option></select></div><div className="chart-area"><div className="chart-y"><span>800</span><span>600</span><span>400</span><span>200</span><span>0</span></div><div className="chart-bars">{[44,58,53,76,68,87,72].map((h,i)=><div key={i}><i style={{height:`${h}%`}}><span>{h*8}</span></i><small>{['Jum','Sab','Min','Sen','Sel','Rab','Kam'][i]}</small></div>)}</div></div></article><article className="moderation-queue"><div className="card-heading"><div><span className="eyebrow">PERLU PERHATIAN</span><h2>Moderasi</h2></div><Badge tone="warning">8 antrean</Badge></div><div className="moderation-list"><button><span className="mod-icon danger"><ShieldAlert/></span><span><strong>Indikasi credential publik</strong><small>Listing #P-8219 • 8 menit</small></span><ArrowRight/></button><button><span className="mod-icon warning"><FileWarning/></span><span><strong>Deskripsi mencurigakan</strong><small>Listing #P-8204 • 24 menit</small></span><ArrowRight/></button><button><span className="mod-icon info"><AlertTriangle/></span><span><strong>3 laporan user baru</strong><small>Akun @bimoarga • 1 jam</small></span><ArrowRight/></button></div><button className="btn btn--secondary" onClick={()=>setTab('listings')}>Buka antrean moderasi</button></article></section>
      <section className="admin-recent"><div className="card-heading"><div><span className="eyebrow">AUDIT STREAM</span><h2>Aktivitas terbaru</h2></div><button>Unduh log</button></div><div className="audit-list">{[['Paket diperbarui','Admin Nara memperbarui “Cookie Premkum”','2 menit',Check,'success'],['User ditangguhkan','Admin Dimas menangguhkan @bimoarga','18 menit',ShieldAlert,'danger'],['Refund diperbarui','Order LGR-82981 menjadi Refunded','44 menit',CircleDollarSign,'info'],['Kategori dibuat','Kategori “Education” ditambahkan','2 jam',Package,'neutral']].map(([title,text,time,Icon,tone],i)=><div key={i}><span className={`audit-icon ${tone}`}><Icon/></span><span><strong>{String(title)}</strong><small>{String(text)}</small></span><time>{String(time)} lalu</time></div>)}</div></section>
    </>}

    {tab==='users'&&<section className="admin-data"><div className="admin-data__head"><div><span className="eyebrow">USER MANAGEMENT</span><h2>Pengguna & akses</h2></div><Input label="Cari pengguna" name="admin-user-search" icon={<Search/>} placeholder="Nama, email, username…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Pengguna</th><th>Role</th><th>Status</th><th>Order</th><th>Bergabung</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><span className="admin-user"><i>{u.name.slice(0,2).toUpperCase()}</i><span><strong>{u.name}</strong><small>@{u.username} • {u.email}</small></span></span></td><td><Badge>{u.role}</Badge></td><td><Badge tone={u.status==='active'?'success':u.status==='review'?'warning':'error'}>{u.status==='active'?'Aktif':u.status==='review'?'Review':'Ditangguhkan'}</Badge></td><td>{u.orders}</td><td>{u.joined}</td><td><button className="btn btn--ghost btn--sm" onClick={()=>setAction({type:u.status==='suspended'?'restore':'suspend',id:u.id,label:u.name})}>{u.status==='suspended'?'Pulihkan':'Tangguhkan'}</button></td></tr>)}</tbody></table></div></section>}

    {tab==='listings'&&<section className="admin-data"><div className="admin-data__head"><div><span className="eyebrow">COOKIE PLAN CONTROL</span><h2>Tiga paket resmi</h2></div><div className="admin-filter-pills"><button className="active">Menunggu <span>8</span></button><button>Dilaporkan <span>3</span></button><button>Semua</button></div></div><div className="review-list">{products.slice(0,4).map((p,i)=><article key={p.id}><span className={`listing-art ${p.accent}`}>{p.icon}</span><div><span><Badge>{p.kind}</Badge><small>Dikirim {i+1} jam lalu</small></span><h3>{p.name}</h3><p>{p.description}</p><small>oleh <b>@{p.seller.username}</b> • {rupiah(p.price)}</small></div><div className="risk-box"><small>RISK SCORE</small><strong className={i===1?'warning':''}>{i===1?'MEDIUM':'LOW'}</strong><span>{i===1?'2 indikator':'Tidak terdeteksi'}</span></div><div className="review-actions"><button className="icon-btn" aria-label="Lihat"><Eye/></button><Button variant="secondary" onClick={()=>setAction({type:'reject',id:p.id,label:p.name})}><X/> Tolak</Button><Button onClick={()=>setAction({type:'approve',id:p.id,label:p.name})}><Check/> Setujui</Button></div></article>)}</div></section>}

    {tab==='transactions'&&<section className="admin-data"><div className="admin-data__head"><div><span className="eyebrow">TRANSACTION CONTROL</span><h2>Arus pembayaran</h2></div><Input label="Cari transaksi" name="admin-tx-search" icon={<Search/>} placeholder="Order ID…"/></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Produk</th><th>Nilai</th><th>Status</th><th>Payment check</th><th></th></tr></thead><tbody>{recentOrders.concat([{id:'LGR-81991',productName:'Cookie Basic',productIcon:'B',date:'1 Agu 2026',price:25000,status:'refunded'}]).map(o=><tr key={o.id}><td><strong>{o.id}</strong><small>{o.date}</small></td><td>{o.productName}</td><td>{rupiah(o.price)}</td><td><StatusBadge status={o.status}/></td><td><span className="server-check"><BadgeCheck/> Server verified</span></td><td><button className="icon-btn"><MoreHorizontal/></button></td></tr>)}</tbody></table></div></section>}

    <Modal open={!!action} onClose={()=>setAction(null)} title={action?.type==='suspend'?'Tangguhkan akun?':action?.type==='restore'?'Pulihkan akun?':action?.type==='approve'?'Setujui listing?':'Tolak listing?'} eyebrow="ADMIN ACTION / AUDITED" footer={<><Button variant="secondary" onClick={()=>setAction(null)}>Batal</Button><Button variant={action?.type==='suspend'||action?.type==='reject'?'danger':'primary'} loading={loading} onClick={execute}>Konfirmasi aksi</Button></>}><div className="admin-confirm"><ShieldAlert/><p>Aksi terhadap <strong>{action?.label}</strong> akan langsung berlaku. Identitas admin, waktu, dan alasan akan disimpan pada audit log.</p><label className="field"><span className="field__label">Catatan internal</span><textarea rows={3} placeholder="Jelaskan alasan tindakan…"/></label></div></Modal>
  </div>
}
